# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bo Frese
tagline:             'Agile/Lean Developer'
description:         'Asorted mix of development related notes'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Bo Free
  url:               http://i-con.dk/
  email:             bo.frese@i-con.dk

# Custom vars
version:             1.0.0
